### ISSUE TITLE
ITUNES

### ISSUE THREAD

**Issue by PANOSPAP1982** [arjndr/itunes-albumart#6]
hello my friend!!!tell me please this is for searching music...songs and albums from itunes?and if yes,please could you make a web version?I am begging you!!!unfortunately I have no idea how to do it!!!

**Comment by arjndr** [comment]
This library is only for fetching [album artworks](https://en.wikipedia.org/wiki/Album_cover) of songs or albums available on iTunes. If you mean streaming songs you can check out [MusicKitJS](https://developer.apple.com/documentation/musickitjs/)

**Comment by PANOSPAP1982** [comment]
HELLO MANNNNNNNNN!!!!NO,STREAMING...JUST RESULTS!!!!BUT PLEASEEEEEEEE I AM BEGGING YOU CAN YOU RELEASE IT?I HAVE NO IDEA FROM DEVELOPING AND I DONT KNOW HOW TO DO IT!!!!PLEASEEEEEEEEE

**Comment by arjndr** [comment]
What exactly are you looking for? Tell me more details and maybe I can help you.

**Comment by PANOSPAP1982** [comment]
YES,OF COURSEEEEEEE....AND THANKS SO MUCH!!!!MY FRIEND I LOVE SPANISH MUSIC SO MUCH!!!AND I NEED ONE WEB WHERE SHOWS ALBUMS AND SONGS FROM ITUNES...WITHOUT STREAMING.PLEASE MY FRIEND BECAUSE I HAVE NO IDEA FROM PROGRAMMING AND DEVELOPING CAN YOU MAKE A WEB VERSION?I PRECIATE IT SO MUCH MAN
